// GENERATED by scripts/extract-copy.mjs from the reference prototypes in
// "EdCloud Website/design_handoff_edcloud_site/reference". Do not hand-edit; re-run the script instead.
// Copy that lives in content.js (logos, press, capabilities, services, cases, proof, phases, results)
// is NOT duplicated here. Reference hrefs like "EdCloud About.dc.html" are mapped to routes in content/site.ts.
export const SHARED = {
  "wordmark": "EDCLOUD VENTURE PARTNERS",
  "markSrc": "https://static.wixstatic.com/media/c8e843_8fd79574ca964055ac18a120887cc9e8~mv2.png/v1/fill/w_32,h_32,al_c,q_85,enc_avif,quality_auto/55b97715067563_5628c905b5051_edited_edited.png",
  "markAlt": "EdCloud mark",
  "navLinks": [
    {
      "label": "About",
      "href": "EdCloud About.dc.html"
    },
    {
      "label": "Services & Results",
      "href": "EdCloud Services.dc.html"
    },
    {
      "label": "Contact",
      "href": "EdCloud Home.dc.html"
    }
  ],
  "mobileMenu": [
    {
      "label": "Home",
      "href": "EdCloud Home.dc.html"
    },
    {
      "label": "About",
      "href": "EdCloud About.dc.html"
    },
    {
      "label": "Services & Results",
      "href": "EdCloud Services.dc.html"
    },
    {
      "label": "Privacy Policy",
      "href": "https://www.edcloud.org/privacy-policy"
    },
    {
      "label": "Accessibility Statement",
      "href": "https://www.edcloud.org/accessibility-statement"
    }
  ],
  "footer": {
    "col1": [
      {
        "tag": "a",
        "text": "Contact",
        "href": "EdCloud Home.dc.html",
        "ariaLabel": null,
        "svgPath": null
      },
      {
        "tag": "a",
        "text": "Book a Meeting",
        "href": "https://calendly.com/aaronsokol/15",
        "ariaLabel": null,
        "svgPath": null
      },
      {
        "tag": "a",
        "text": "info@edcloud.org",
        "href": "mailto:info@edcloud.org",
        "ariaLabel": null,
        "svgPath": null
      },
      {
        "tag": "span",
        "text": "28 Geary St. Ste 650",
        "href": null,
        "ariaLabel": null,
        "svgPath": null
      },
      {
        "tag": "span",
        "text": "San Francisco, CA 94108",
        "href": null,
        "ariaLabel": null,
        "svgPath": null
      },
      {
        "tag": "span",
        "text": "Tel: 510-306-2403",
        "href": null,
        "ariaLabel": null,
        "svgPath": null
      },
      {
        "tag": "span",
        "text": "Fax: 510-306-2403",
        "href": null,
        "ariaLabel": null,
        "svgPath": null
      },
      {
        "tag": "a",
        "text": "",
        "href": "https://www.linkedin.com/company/edcloud-llc",
        "ariaLabel": "LinkedIn",
        "svgPath": "M20.45 20.45h-3.56v-5.57c0-1.33-.02-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.34V9h3.42v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.07 2.07 0 1 1 0-4.13 2.07 2.07 0 0 1 0 4.13zM7.12 20.45H3.55V9h3.57v11.45z"
      }
    ],
    "col2": [
      {
        "tag": "a",
        "text": "Navigate",
        "href": "EdCloud Home.dc.html"
      },
      {
        "tag": "a",
        "text": "About",
        "href": "EdCloud About.dc.html"
      },
      {
        "tag": "a",
        "text": "Services & Results",
        "href": "EdCloud Services.dc.html"
      },
      {
        "tag": "a",
        "text": "Privacy Policy",
        "href": "https://www.edcloud.org/privacy-policy"
      },
      {
        "tag": "a",
        "text": "Accessibility Statement",
        "href": "https://www.edcloud.org/accessibility-statement"
      }
    ],
    "brand": "EdCloud Venture Partners",
    "copyright": "© 2026 by EdCloud, LLC"
  },
  "newsletter": {
    "title": "Subscribe",
    "body": "Stay at the forefront of innovation. Sign up for our newsletter and receive exclusive insights, project updates, and industry news delivered straight to your inbox.",
    "emailLabel": "Email*",
    "consentLabel": "Yes, subscribe me to your newsletter.",
    "submit": "SUBMIT",
    "links": [
      {
        "label": "About",
        "href": "EdCloud About.dc.html"
      },
      {
        "label": "Services & Results",
        "href": "EdCloud Services.dc.html"
      }
    ]
  }
} as const;

export const HOME_COPY = {
  "meta": {
    "title": "EdCloud Venture Partners | Growth Consulting",
    "description": "Trusted by Handshake, Clever, Outschool, & Wayfinder - EdCloud Venture Partners helps scale education technology companies from foothold to national ubiquity with field-proven marketing and sales expertise."
  },
  "hero": {
    "posterSrc": "https://static.wixstatic.com/media/11062b_aa9be95a5d7c43ca974ea1c773b8803df000.jpg/v1/fill/w_1920,h_1080,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/11062b_aa9be95a5d7c43ca974ea1c773b8803df000.jpg",
    "posterAlt": "Students working together on a campus",
    "videoSrc": "https://video.wixstatic.com/video/11062b_aa9be95a5d7c43ca974ea1c773b8803d/1080p/mp4/file.mp4",
    "h1Lines": [
      "We Bring Great",
      "Education Companies",
      "to National Scale."
    ],
    "p": "EdCloud Venture Partners supercharges post-traction education innovation teams that are actively reinventing instruction, administration, and the student experience - delivering dramatic impact through rapid, sustainable growth."
  },
  "titles": [
    {
      "n": "01",
      "title": "Our Promise",
      "tag": "h2"
    },
    {
      "n": "02",
      "title": "Services & Results",
      "tag": "h2"
    },
    {
      "n": "03",
      "title": "Featured Projects",
      "tag": "h2"
    },
    {
      "n": "04",
      "title": "Deliverables",
      "tag": "h2"
    },
    {
      "n": "05",
      "title": "Press",
      "tag": "h2"
    },
    {
      "n": "06",
      "title": "Select Clients",
      "tag": "h1"
    },
    {
      "n": "07",
      "title": "Contact Us",
      "tag": "h2"
    }
  ],
  "promise": {
    "lead": "Our core team has led hyperspeed expansion efforts at some of the most successful K12 and higher education technology companies in the world - and helped dozens of startups, corporations, nonprofit organizations, school districts, and universities build replicable solutions for long-term growth.",
    "p2": "With decades of proven experience, our expert advisers can help you fundraise, expand into new markets, build and organize a growth strategy, pressure test a tactical playbook, and execute swiftly - expanding your reach with maximum efficiency. We build industry and consumer-side engagement strategies, marketing programs, and sales pipelines - the vital elements of any successful growth effort.",
    "p3": "Our partnerships focus on strategic planning, go-to-market expansion, tactical execution, team development and training, sales operations, and intelligent pipeline automation. If this strikes a chord, we'd love to get in touch.",
    "readMore": "Read More"
  },
  "servicesLink": "Services & Results",
  "deliverables": {
    "lead": "EdCloud can help with everything it takes to move from founder-led sales to a momentum growth engine that never stops working.",
    "imgSrc": "/images/conference-room.jpg",
    "imgAlt": "Educators at a district conference"
  },
  "press": {
    "linkLabel": "Read The Full Article",
    "figureSrc": "https://static.wixstatic.com/media/11062b_51f3741c03264d3ebb42126cfb510510~mv2.jpg/v1/fill/w_1450,h_700,q_90,enc_avif,quality_auto/11062b_51f3741c03264d3ebb42126cfb510510~mv2.jpg",
    "figureAlt": "University campus building"
  },
  "contact": {
    "imgSrc": "https://static.wixstatic.com/media/31d0a93857b149b5ab12ec952dde0516.jpg/v1/fill/w_980,h_653,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Classroom%20Lecture.jpg",
    "imgAlt": "Classroom Lecture",
    "h2Lines": [
      "Ready to get going?",
      "Get in touch."
    ],
    "fields": [
      {
        "label": "First name*",
        "id": "c-first",
        "name": "c-first",
        "type": "text",
        "required": true
      },
      {
        "label": "Last name*",
        "id": "c-last",
        "name": "c-last",
        "type": "text",
        "required": true
      },
      {
        "label": "Email*",
        "id": "c-email",
        "name": "c-email",
        "type": "email",
        "required": true
      },
      {
        "label": "Phone",
        "id": "c-phone",
        "name": "c-phone",
        "type": "tel",
        "required": false
      },
      {
        "label": "Message",
        "id": "c-message",
        "name": "c-message",
        "type": "textarea",
        "required": false
      }
    ],
    "submit": "SUBMIT"
  }
} as const;

export const ABOUT_COPY = {
  "meta": {
    "title": "About | EdCloud Venture Partners",
    "description": "EdCloud Venture Partners helps post-traction education technology companies scale nationally with operator-led strategy, buyer-centric positioning, sales systems, procurement support, pricing optimization, and RevOps infrastructure to drive predictable growth, stronger adoption, and measurable impact in K-12 and higher education."
  },
  "hero": {
    "imgSrc": "https://static.wixstatic.com/media/11062b_c4449fb00d5143e5bdb41c3924c507ff~mv2_d_4166_2343_s_2.jpg/v1/fill/w_1920,h_1080,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/11062b_c4449fb00d5143e5bdb41c3924c507ff~mv2_d_4166_2343_s_2.jpg",
    "imgAlt": "Technology Class",
    "h1": "About Us"
  },
  "titles": [
    {
      "n": "01",
      "title": "Mission & History",
      "tag": "h2"
    },
    {
      "n": "02",
      "title": "Managing Partner",
      "tag": "h2"
    },
    {
      "n": "03",
      "title": "By The Numbers",
      "tag": "h2"
    }
  ],
  "mission": [
    {
      "tag": "h2",
      "text": "About EdCloud"
    },
    {
      "tag": "p",
      "text": "EdCloud exists for a simple reason: too many promising education products stall out somewhere between \"brilliant pilot\" and \"truly transformational scale.\" The path from the first hundred students to thousands of schools and hundreds of universities is not just a matter of “more sales.” It’s a discipline - part art, part infrastructure - requiring clear positioning, the right routes to market, procurement fluency, and the operational muscle to deliver results consistently. We built EdCloud to be that force multiplier for early stage teams who are ready to make the leap."
    },
    {
      "tag": "h3",
      "text": "Our mission"
    },
    {
      "tag": "p",
      "text": "We partner with post-traction education technology companies (typically in the $0 to $1M ARR range) and help them reach $20M+ ARR faster and more predictably. Our mission is to bring great education companies to national scale without compromising product quality, student outcomes, or institutional trust. When we succeed, faculty and staff get tools that actually help, learners see better results, and institutions get new technology that resets their boundaries and dramatically amplifies their impact."
    },
    {
      "tag": "h3",
      "text": "How we think about scale"
    },
    {
      "tag": "p",
      "text": "Scaling in education is different. Districts and universities don’t move like consumer markets or typical SMB sales. Trust of outsiders is low, adoption is multi-stakeholder, budgets are earmarked, procurement rules matter, and credibility is earned by delivering value across a full academic cycle. We’ve learned (and proved) that the fastest route to scale in this domain is clarity, reliability, and repeatability:"
    },
    {
      "tag": "ul",
      "items": [
        {
          "text": "Clarity about who you serve, the precise value you create for each stakeholder, and why you’re the inevitable choice."
        },
        {
          "text": "Repeatability that creates pipeline, converts small contracts to massive deals, navigates legal and security reviews, and lets you renew and expand with ease."
        }
      ]
    },
    {
      "tag": "p",
      "text": "Everything we do at EdCloud connects back to those two ideas."
    },
    {
      "tag": "h3",
      "text": "Our approach (operator first, not just advisory)"
    },
    {
      "tag": "p",
      "text": "We operate with sleeves-rolled-up pragmatism. Yes, we craft strategy; more importantly, we turn that strategy into a working system your team can run. And, when you need it, we actually run the system."
    },
    {
      "tag": "ul",
      "items": [
        {
          "lead": "Define the narrative:",
          "text": "we refine positioning and messaging until it’s unmistakably buyer-centric, battle-tested in live conversations, and supported by proof your prospects care about."
        },
        {
          "lead": "Build the machine:",
          "text": "we stand up a national sales engine for K12 and higher ed rollouts: territory plans, account lists, sequences, demo flows, partner channels, and the collateral that moves deals forward."
        },
        {
          "lead": "Make procurement eas:",
          "text": "we reduce friction with RFP playbooks, sole-source/justification language, security/privacy documentation, and contracting guidance that respects institutional realities."
        },
        {
          "lead": "Monetize responsibly:",
          "text": "we align pricing and packaging with value delivered and with how institutions actually buy. Opportunities that convert, tiers that scale, and guardrails that protect margins."
        },
        {
          "lead": "Institutionalize success:",
          "text": "we implement RevOps scaffolding - solid GTME, crisp stage definitions, forecasting hygiene, enablement, onboarding, and success metrics - so growth becomes durable and forecastable."
        }
      ]
    },
    {
      "tag": "p",
      "text": "The cadence is tight: focus sprints, fast experimentation, clear owner/metric for every workstream, and weekly evidence of progress. We move quickly, but we don’t cut corners that will cost you in year two."
    },
    {
      "tag": "h3",
      "text": "A brief history"
    },
    {
      "tag": "p",
      "text": "EdCloud started informally, helping friends at early-stage companies transform early traction into massive scale. Along the way we partnered with teams behind widely adopted platforms in K12 and higher ed, honing a playbook that worked across different products, price points, and buyer types. What began as a series of “can you help us get from here to there?” engagements became a dedicated practice with a singular focus: quickly scaling education companies that deserve to grow."
    },
    {
      "tag": "p",
      "text": "As the portfolio of wins piled up, so did our conviction: the market didn’t need another consultancy writing decks; it needed operators who could design the system, build it, and turn it on - and then teach an internal team to run it long after we’re gone. That’s the our approach today."
    },
    {
      "tag": "h3",
      "text": "Who we serve"
    },
    {
      "tag": "p",
      "text": "We work with seed to Series B teams selling into K12 districts,colleges and universities, and workforce/enterprise learning programs. Ideal partners have meaningful early traction (a product that solves a real problem for students, educators, or administrators) and are ready to transition from founder-led sales to a repeatable revenue engine. We’re especially effective when stakes are high: multi-district deployments, campus-wide rollouts, and go-to-market pivots where the cost of getting it wrong is measured in lost academic years."
    },
    {
      "tag": "h3",
      "text": "What success looks like"
    },
    {
      "tag": "p",
      "text": "Outcomes vary by company, but the pattern is consistent: sharper win rates from a clearer story; faster cycles because procurement is de-risked; healthier unit economics through thoughtful pricing; and a pipeline that doesn’t collapse when the founder steps out of the room. We measure our work the way your board does: pipeline coverage, ARR growth, ASP, cycle time, NRR - and we design for the moment when your internal team can confidently run the playbook without us."
    },
    {
      "tag": "h3",
      "text": "How engagements work"
    },
    {
      "tag": "p",
      "text": "Every engagement starts with a short, focused discovery sprint to align on goals, constraints, and the fastest path to value. From there we enter a 60 to 90 day build phase where we craft the narrative, stand up the sales system, and remove the biggest sources of friction in legal and procurement. We’ll often recruit or upskill the first few hires who will own the motion internally. After the build, many clients keep us on as an advisor or special-projects partner to support major deals, product launches, or partner negotiations. Our aim is not to embed forever; it’s to leave you with a machine that keeps on delivering."
    },
    {
      "tag": "h3",
      "text": "Why now"
    },
    {
      "tag": "p",
      "text": "Education is undergoing a generational platform shift: new models of instructional delivery, tighter links between K12, higher ed, and workforce, and a renewed emphasis on measurable outcomes. Institutions are open to innovation, but they are rightfully demanding about privacy, security, control - and above all, value. That’s the moment EdCloud was built for: translating genuine product value into institution-scale adoption with the speed of a startup and the rigor of a trusted partner."
    }
  ],
  "partner": {
    "imgSrc": "https://static.wixstatic.com/media/c8e843_d6fbe6723c2e4c82a536a7c46f6040f9~mv2.png/v1/fill/w_486,h_450,al_c,q_85,enc_avif,quality_auto/headshot%202.png",
    "imgAlt": "Aaron Sokol",
    "h2": "About Aaron Sokol",
    "paragraphs": [
      "Aaron Sokol is the founder and Managing Partner of EdCloud Venture Partners, a California-based growth consultancy that helps post-traction education technology companies scale from early traction to national adoption. With 20+ years in education finance, edtech, and enterprise sales and marketing, Aaron has helped build and lead high-capacity growth teams at companies like Handshake, Clever, Edvisorly, Wayfinder, and GiveCampus - guiding them from initial foothold to category leadership across K-12 and higher ed.",
      "Aaron is based in San Francisco, where he lives with his wife and kids."
    ]
  },
  "numbers": [
    {
      "stat": "22",
      "title": "Years of Experience",
      "body": "A proven track record of success in education technology marketing and sales"
    },
    {
      "stat": "14",
      "title": "Ongoing Projects",
      "body": "Actively engaged in driving innovation across diverse areas."
    },
    {
      "stat": "2",
      "title": "Provisional Patents",
      "body": "Recognition for groundbreaking technological advancements and innovative approaches."
    },
    {
      "stat": "8",
      "title": "Dedicated Professionals",
      "body": "A team of passionate and skilled operators, experts, and engineers."
    }
  ]
} as const;

export const SERVICES_COPY = {
  "meta": {
    "title": "Services & Results | EdCloud Venture Partners",
    "description": "EdCloud helps post-traction education technology companies scale with research-driven go-to-market strategy, buyer insights, pricing and packaging, sales engine design, channel partnerships, smarter procurement paths, and RevOps systems that accelerate adoption in K-12 and higher education markets."
  },
  "hero": {
    "imgSrc": "https://static.wixstatic.com/media/11062b_73e69c0bfc9b49ce8e001cc70aeeb043~mv2.jpeg/v1/fill/w_1920,h_1080,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/11062b_73e69c0bfc9b49ce8e001cc70aeeb043~mv2.jpeg",
    "imgAlt": "Modern Classroom",
    "h1": "Services & Results",
    "p": "Six operator-run services that take an education company from early traction to national scale. Every one is measured the way your board measures it: pipeline, ARR, ASP, cycle time, NRR."
  },
  "titles": [
    {
      "n": "01",
      "title": "How an engagement works",
      "tag": "h2"
    },
    {
      "n": "02",
      "title": "What we do",
      "tag": "h2"
    },
    {
      "n": "03",
      "title": "Results",
      "tag": "h2"
    },
    {
      "n": "04",
      "title": "Is this a fit",
      "tag": "h2"
    }
  ],
  "engagementLead": "We are operators, not advisers. We design the system, build it, turn it on, and then train your team to run it without us. Three phases, each with a named owner and a weekly metric.",
  "whatWeDoLead": "Most clients start with one or two of these. The engine and the operations layer are where the compounding happens.",
  "dlLabels": [
    "Best for",
    "You get",
    "Timeline"
  ],
  "resultsLead": "Four engagements, four starting points, one pattern: a clearer story, a de-risked purchase path, and a pipeline that no longer depends on the founder being in the room.",
  "tableHead": [
    "Client",
    "Where we started",
    "What we built",
    "Outcome"
  ],
  "fit": [
    {
      "title": "We are the right partner when",
      "items": [
        "You sell to K12 districts, colleges and universities, or workforce learning programs.",
        "You are seed to Series B, roughly $0 to $1M ARR, with a product real users already rely on.",
        "Sales still runs through the founder and you need it to run through a team.",
        "The next deals are multi-district or campus-wide, and getting them wrong costs an academic year."
      ]
    },
    {
      "title": "We are probably not when",
      "items": [
        "You are pre-product, or still searching for the first paying customers.",
        "You want a strategy deck rather than a working system with someone accountable for it.",
        "Your buyers are consumers or small businesses rather than institutions."
      ]
    }
  ],
  "start": {
    "n": "05",
    "h2": "Start with a 15 minute call.",
    "cta": {
      "label": "BOOK A MEETING",
      "href": "https://calendly.com/aaronsokol/15"
    },
    "email": {
      "label": "info@edcloud.org",
      "href": "mailto:info@edcloud.org"
    }
  }
} as const;
