"""Cut the art-directed mobile crops that components/Picture.tsx serves below 1024px.

The desktop photos are fixed landscape crops (the heroes are 1920x1080), and phones used to get
those whole files: a 1920px landscape poster squeezed into a portrait screen. This reads
scripts/images/crops.json (one entry per crop: source, ratio, focal point, srcset widths), cuts
each crop around its focal point, and writes

    public/images/m/{name}-{W}x{H}-{width}.webp     WebP quality 76, method 6
    components/crops.generated.ts                   every crop's URLs and pixel sizes, for Picture

It never upscales: a requested width wider than the crop itself becomes the crop's own width.
Deterministic and safe to re-run: each output is encoded in memory and only written when its
bytes differ from what is on disk, so an unchanged run touches nothing. Stale files in
public/images/m are reported, not deleted.

    python scripts/images/build-crops.py
"""
import io, json, os, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC_DIR = os.path.join(ROOT, 'public', 'images')
OUT_DIR = os.path.join(SRC_DIR, 'm')
TS_OUT = os.path.join(ROOT, 'components', 'crops.generated.ts')
URL_BASE = '/images/m/'
QUALITY, METHOD = 76, 6
SLOTS = ('phone', 'tablet')


def crop_box(w, h, rw, rh, fx, fy):
    """The largest rw:rh box inside w x h whose centre is as close to (fx*w, fy*h) as the frame allows."""
    if w * rh > h * rw:  # source is wider than the target ratio: full height, cut the sides
        cw, ch = round(h * rw / rh), h
    else:  # taller: full width, cut top and bottom
        cw, ch = w, round(w * rh / rw)
    x0 = min(max(round(fx * w - cw / 2), 0), w - cw)
    y0 = min(max(round(fy * h - ch / 2), 0), h - ch)
    return x0, y0, x0 + cw, y0 + ch


def write_if_changed(path, data):
    if os.path.exists(path):
        with open(path, 'rb') as f:
            if f.read() == data:
                return False
    with open(path, 'wb') as f:
        f.write(data)
    return True


def main():
    with open(os.path.join(HERE, 'crops.json'), encoding='utf-8') as f:
        spec = json.load(f)['crops']
    os.makedirs(OUT_DIR, exist_ok=True)

    table = {}  # name -> slot -> {ratio, files}
    written, kept, expected = 0, 0, set()
    for entry in spec:
        rw, rh = (int(v) for v in entry['ratio'].split(':'))
        src = Image.open(os.path.join(SRC_DIR, entry['src']))
        src = src.convert('RGB')
        box = crop_box(src.width, src.height, rw, rh, entry.get('focusX', 0.5), entry.get('focusY', 0.5))
        cropped = src.crop(box)
        cw, ch = cropped.size
        widths = sorted({min(w, cw) for w in entry['widths']})
        files = []
        for w in widths:
            h = round(w * ch / cw)
            out = cropped if (w, h) == (cw, ch) else cropped.resize((w, h), Image.LANCZOS)
            buf = io.BytesIO()
            out.save(buf, 'WEBP', quality=QUALITY, method=METHOD)
            fname = f"{entry['name']}-{rw}x{rh}-{w}.webp"
            expected.add(fname)
            changed = write_if_changed(os.path.join(OUT_DIR, fname), buf.getvalue())
            written, kept = written + changed, kept + (not changed)
            files.append({'url': URL_BASE + fname, 'w': w, 'h': h})
            print(f"{'wrote' if changed else 'same '} {fname:40s} {w}x{h}  {len(buf.getvalue()) / 1024:6.1f} KB")
        for slot in entry['slots']:
            if slot not in SLOTS:
                sys.exit(f"{entry['name']}: unknown slot {slot!r}")
            if slot in table.setdefault(entry['name'], {}):
                sys.exit(f"{entry['name']}: slot {slot!r} defined twice")
            table[entry['name']][slot] = {'ratio': entry['ratio'], 'files': files}

    for name, slots in table.items():
        missing = [s for s in SLOTS if s not in slots]
        if missing:
            sys.exit(f"{name}: no crop for {', '.join(missing)}")

    lines = [
        '// Generated by scripts/images/build-crops.py from scripts/images/crops.json. Do not edit by hand:',
        '// change crops.json and re-run `python scripts/images/build-crops.py`.',
        '',
        'export type CropFile = { readonly url: string; readonly w: number; readonly h: number };',
        'export type Crop = { readonly ratio: string; readonly files: readonly CropFile[] };',
        '',
        'export const CROPS = {',
    ]
    for name in sorted(table):
        lines.append(f"  '{name}': {{")
        for slot in SLOTS:
            c = table[name][slot]
            lines.append(f"    {slot}: {{")
            lines.append(f"      ratio: '{c['ratio']}',")
            lines.append('      files: [')
            for fl in c['files']:
                lines.append(f"        {{ url: '{fl['url']}', w: {fl['w']}, h: {fl['h']} }},")
            lines.append('      ],')
            lines.append('    },')
        lines.append('  },')
    lines += [
        '} as const satisfies Record<string, { phone: Crop; tablet: Crop }>;',
        '',
        'export type CropName = keyof typeof CROPS;',
        '',
    ]
    ts_changed = write_if_changed(TS_OUT, '\n'.join(lines).encode('utf-8'))

    stale = sorted(set(os.listdir(OUT_DIR)) - expected)
    print(f"\n{written} written, {kept} unchanged; crops.generated.ts {'written' if ts_changed else 'unchanged'}")
    if stale:
        print('Not produced by crops.json any more (delete if unused): ' + ', '.join(stale))


if __name__ == '__main__':
    main()
