// Generated by scripts/images/build-crops.py from scripts/images/crops.json. Do not edit by hand:
// change crops.json and re-run `python scripts/images/build-crops.py`.

export type CropFile = { readonly url: string; readonly w: number; readonly h: number };
export type Crop = { readonly ratio: string; readonly files: readonly CropFile[] };

export const CROPS = {
  'aaron-sokol': {
    phone: {
      ratio: '4:5',
      files: [
        { url: '/images/m/aaron-sokol-4x5-256.webp', w: 256, h: 320 },
        { url: '/images/m/aaron-sokol-4x5-360.webp', w: 360, h: 450 },
      ],
    },
    tablet: {
      ratio: '4:5',
      files: [
        { url: '/images/m/aaron-sokol-4x5-256.webp', w: 256, h: 320 },
        { url: '/images/m/aaron-sokol-4x5-360.webp', w: 360, h: 450 },
      ],
    },
  },
  'classroom-lecture': {
    phone: {
      ratio: '39:14',
      files: [
        { url: '/images/m/classroom-lecture-39x14-480.webp', w: 480, h: 172 },
        { url: '/images/m/classroom-lecture-39x14-828.webp', w: 828, h: 297 },
        { url: '/images/m/classroom-lecture-39x14-980.webp', w: 980, h: 352 },
      ],
    },
    tablet: {
      ratio: '21:9',
      files: [
        { url: '/images/m/classroom-lecture-21x9-980.webp', w: 980, h: 420 },
      ],
    },
  },
  'conference-room': {
    phone: {
      ratio: '16:9',
      files: [
        { url: '/images/m/conference-room-16x9-480.webp', w: 480, h: 270 },
        { url: '/images/m/conference-room-16x9-828.webp', w: 828, h: 466 },
        { url: '/images/m/conference-room-16x9-1170.webp', w: 1170, h: 658 },
      ],
    },
    tablet: {
      ratio: '3:2',
      files: [
        { url: '/images/m/conference-room-3x2-1200.webp', w: 1200, h: 800 },
      ],
    },
  },
  'hero-about': {
    phone: {
      ratio: '4:5',
      files: [
        { url: '/images/m/hero-about-4x5-480.webp', w: 480, h: 600 },
        { url: '/images/m/hero-about-4x5-828.webp', w: 828, h: 1035 },
        { url: '/images/m/hero-about-4x5-864.webp', w: 864, h: 1080 },
      ],
    },
    tablet: {
      ratio: '3:2',
      files: [
        { url: '/images/m/hero-about-3x2-1200.webp', w: 1200, h: 800 },
        { url: '/images/m/hero-about-3x2-1600.webp', w: 1600, h: 1067 },
      ],
    },
  },
  'hero-poster': {
    phone: {
      ratio: '4:5',
      files: [
        { url: '/images/m/hero-poster-4x5-480.webp', w: 480, h: 600 },
        { url: '/images/m/hero-poster-4x5-828.webp', w: 828, h: 1035 },
        { url: '/images/m/hero-poster-4x5-864.webp', w: 864, h: 1080 },
      ],
    },
    tablet: {
      ratio: '3:2',
      files: [
        { url: '/images/m/hero-poster-3x2-1200.webp', w: 1200, h: 800 },
        { url: '/images/m/hero-poster-3x2-1600.webp', w: 1600, h: 1067 },
      ],
    },
  },
  'hero-services': {
    phone: {
      ratio: '4:5',
      files: [
        { url: '/images/m/hero-services-4x5-480.webp', w: 480, h: 600 },
        { url: '/images/m/hero-services-4x5-828.webp', w: 828, h: 1035 },
        { url: '/images/m/hero-services-4x5-864.webp', w: 864, h: 1080 },
      ],
    },
    tablet: {
      ratio: '3:2',
      files: [
        { url: '/images/m/hero-services-3x2-1200.webp', w: 1200, h: 800 },
        { url: '/images/m/hero-services-3x2-1600.webp', w: 1600, h: 1067 },
      ],
    },
  },
  'stairway': {
    phone: {
      ratio: '39:14',
      files: [
        { url: '/images/m/stairway-39x14-480.webp', w: 480, h: 172 },
        { url: '/images/m/stairway-39x14-828.webp', w: 828, h: 298 },
        { url: '/images/m/stairway-39x14-1170.webp', w: 1170, h: 420 },
      ],
    },
    tablet: {
      ratio: '21:9',
      files: [
        { url: '/images/m/stairway-21x9-1450.webp', w: 1450, h: 621 },
      ],
    },
  },
} as const satisfies Record<string, { phone: Crop; tablet: Crop }>;

export type CropName = keyof typeof CROPS;
